name: CI

on:
    pull_request:
        branches:
            - '*'
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    all:
        name: All

        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest

        runs-on: ${{matrix.os}}

        steps:
            - uses: actions/checkout@v2

            - name: Setup
              run: ./setup.sh

            - name: Install required linux packages
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: sudo apt-get update && sudo apt-get install -y dpkg fakeroot tree

            - name: Install dependencies
              run: npm ci

            - name: Check formatting
              run: npm run format-check

            - name: Build
              run: npm run make

            - name: Publish macOS x64 artifacts
              if: matrix.os == 'macos-latest'
              uses: actions/upload-artifact@v2
              with:
                  name: macos-x64-artifact
                  path: |
                      out/make/zip/darwin/x64/*.zip

            - name: Publish Linux x64 artifacts
              if: matrix.os == 'ubuntu-latest'
              uses: actions/upload-artifact@v2
              with:
                  name: linux-x64-artifact
                  path: |
                      out/make/deb/x64/*.deb
