name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    all:
        name: All

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Download actionlint
              id: actionlint
              run: bash <(curl
                  https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

            - name: Check workflow
              run: ${{ steps.actionlint.outputs.executable }} -color

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Check formatting
              run: npm run format-check
